sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
